resolver: lts-8.6

packages:
  - '.'

extra-deps:
  - proctest-0.1.3.0

flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
