name: Nix Build

on:
  - push
  - pull_request

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          experimental-features = nix-command flakes
          allow-import-from-derivation = true
          accept-flake-config = true
    - uses: cachix/cachix-action@v12
      with:
        name: sgillespie
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Build executable
      run: nix build .
    - name: Run tests
      run: nix build .#gibberish:test:test
    - name: Run static checks
      run: nix build .#fourmoluCheck .#hlintCheck
